import os

#####################################
##### Projeto Escola - Versão 1 #####
#####################################

resp = ''
while resp != '0':
    os.system('clear')
    print("############################################")
    print("######       Projeto SIG-Escola       ######")
    print("############################################")
    print("#####      1 - Módulo Aluno            #####")
    print("#####      2 - Módulo Professor        #####")
    print("#####      3 - Módulo Turma            #####")
    print("#####      4 - Módulo Relatório        #####")
    print("#####      5 - Módulo Informações      #####")
    print("#####      0 - Sair                    #####")
    resp = input("##### Escolha sua opção: ")

    if resp == '1':   
        print()
        print("############################################")
        print("#####     Você está no Módulo Aluno     ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '2':
        print()
        print("############################################")
        print("#####   Você está no Módulo Professor   ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '3':
        print()
        print("############################################")
        print("#####     Você está no Módulo Turma     ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '4':
        print()
        print("############################################")
        print("#####   Você está no Módulo Relatório   ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Este módulo ainda está       ####")
        print("#####        em desenvolvimento         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '5':
        print()
        print("############################################")
        print("#####  Você está no Módulo Informações  ####")
        print("############################################")
        print()
        print("#####  Projeto de Gestão de uma Escola  ####")
        print("#####  Equipe de desenvolvimento:       ####")
        print("#####  * Flavius Gorgônio @flgorgonio   ####")
        print("#####  Licença Pública Geral GNU        ####")
        print("#####  www.gnu.org/licenses/gpl.html    ####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '0':
        print()
        print("############################################")
        print("#####  Você encerrou o programa, até logo! #")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    else:
        print()
        print("############################################")
        print("#####   Você digitou uma opção inválida ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Retorne ao menu anterior     ####")
        print("#####         e tente novamente         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")

print("Fim")
