import os

########################################
##### Sistema BitScola - Versão 4 #####
########################################

op_princ = ''
while op_princ != '0':
    os.system('cls' if os.name == 'nt' else 'clear')
    print("############################################")
    print("######       Sistema BitScola       ######")
    print("############################################")
    print("#####      1 - Módulo Aluno            #####")
    print("#####      2 - Módulo Professor        #####")
    print("#####      3 - Módulo Turma            #####")
    print("#####      4 - Módulo Relatório        #####")
    print("#####      5 - Módulo Informações      #####")
    print("#####      0 - Sair                    #####")
    op_princ = input("##### Escolha sua opção: ")

    if op_princ == '1':
        op_aluno = ''
        while op_aluno != '0':
            os.system('cls' if os.name == 'nt' else 'clear')
            print()
            print("############################################")
            print("#####           Módulo Aluno           #####")
            print("############################################")
            print("##### 1 - Cadastrar Aluno              #####")
            print("##### 2 - Exibir Dados do Aluno        #####")
            print("##### 3 - Alterar Dados do Aluno       #####")
            print("##### 4 - Excluir Aluno                #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_aluno = input("##### Escolha sua opção: ")
            print()
            if op_aluno == '1':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####           Cadastra Aluno         #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                matr = input("##### Matrícula: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Aluno cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '2':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####        Exibe Dados do Aluno      #####")
                print("############################################")
                print()
                matr = input("##### Matrícula: ")
                print()
                print("##### Matrícula:", matr)
                print("##### Nome     : Fulano de Tal dos Anzóis")
                print("##### Email    : fulano.anzois@ufrn.edu.br")
                print("##### Celular  : (84) 88888-4444")
                print()
                print("\t=============================")
                print("\t=          ATENÇÃO          =")
                print("\t=      Dados simulados      =")
                print("\t= Esta funcionalidade ainda =")
                print("\t=  está sendo implementada. =")
                print("\t=============================")
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '3':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####       Altera Dados do Aluno      #####")
                print("############################################")
                print()
                matr = input("##### Matrícula: ")
                print()
                nome = input("##### Nome: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Aluno alterado com sucesso!")
                print()
                print("\t=============================")
                print("\t=          ATENÇÃO          =")
                print("\t=      Dados simulados      =")
                print("\t= Esta funcionalidade ainda =")
                print("\t=  está sendo implementada. =")
                print("\t=============================")
                print()
                print("Aluno alterado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_aluno == '4':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####         Exclui Aluno             #####")
                print("############################################")
                print()
                matr = input("##### Matrícula: ")
                print()
                print("Aluno excluído com sucesso!")
                print()
                print("\t=============================")
                print("\t=          ATENÇÃO          =")
                print("\t=      Dados simulados      =")
                print("\t= Esta funcionalidade ainda =")
                print("\t=  está sendo implementada. =")
                print("\t=============================")
                print()
                print("Aluno excluído com sucesso!")
                input("Tecle <ENTER> para continuar...")
    
    elif op_princ == '2':
        op_prof = ''
        while op_prof != '0':
            os.system('cls' if os.name == 'nt' else 'clear')
            print()
            print("############################################")
            print("#####         Módulo Professor         #####")
            print("############################################")
            print("##### 1 - Cadastrar Professor          #####")
            print("##### 2 - Exibir Dados do Professor    #####")
            print("##### 3 - Alterar Dados do Professor   #####")
            print("##### 4 - Excluir Professor            #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_prof = input("##### Escolha sua opção: ")
            print()
            if op_prof == '1':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####         Cadastra Professor       #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                cpf = input("##### CPF: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Professor cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '2':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####      Exibe Dados do Professor    #####")
                print("############################################")
                print()
                cpf = input("##### CPF: ")
                print()
                print("##### CPF    :", cpf)
                print("##### Nome   : Beltrano de Qual dos Lençóis")
                print("##### Email  : beltrano.lencois@ufrn.edu.br")
                print("##### Celular: (84) 77777-5555")
                print()
                print("\t=============================")
                print("\t=          ATENÇÃO          =")
                print("\t=      Dados simulados      =")
                print("\t= Esta funcionalidade ainda =")
                print("\t=  está sendo implementada. =")
                print("\t=============================")
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '3':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####     Altera Dados do Professor    #####")
                print("############################################")
                print()
                nome = input("##### Nome: ")
                print()
                cpf = input("##### CPF: ")
                print()
                email = input("##### Email: ")
                print()
                fone = input("##### Celular: ")
                print()
                print("Professor alterado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_prof == '4':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####       Exclui Professor           #####")
                print("############################################")
                print()
                cpf = input("##### CPF: ")
                print()
                print("Professor excluído com sucesso!")
                input("Tecle <ENTER> para continuar...")
    
    elif op_princ == '3':
        op_turma = ''
        while op_turma != '0':
            os.system('cls' if os.name == 'nt' else 'clear')
            print()
            print("############################################")
            print("#####           Módulo Turma           #####")
            print("############################################")
            print("##### 1 - Cadastrar Turma              #####")
            print("##### 2 - Exibir Dados da Turma        #####")
            print("##### 3 - Alterar Dados da Turma       #####")
            print("##### 4 - Excluir Turma                #####")
            print("##### 0 - Retornar ao Menu Principal   #####")
            op_turma = input("##### Escolha sua opção: ")
            print()
            if op_turma == '1':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####           Cadastra Turma         #####")
                print("############################################")
                print()
                nome_turma = input("##### Nome da Turma: ")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                horario = input("##### Horário das Aulas: ")
                print()
                cpf_prof = input("##### CPF do Professor: ")
                print()
                print("Professor cadastrado com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '2':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####        Exibe Dados da Turma      #####")
                print("############################################")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                print("##### Código   :", cod_turma)
                print("##### Turma    : Matemática Insana")
                print("##### Horário  : Seg a Sexta, das 7h às 22h")
                print("##### Professor: Márcio Barbosa dos Anzóis")
                print()
                print("\t=============================")
                print("\t=          ATENÇÃO          =")
                print("\t=      Dados simulados      =")
                print("\t= Esta funcionalidade ainda =")
                print("\t=  está sendo implementada. =")
                print("\t=============================")
                print()
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '3':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####       Altera Dados da Turma      #####")
                print("############################################")
                print()
                nome_turma = input("##### Nome da Turma: ")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                horario = input("##### Horário das Aulas: ")
                print()
                cpf_prof = input("##### CPF do Professor: ")
                print()
                print("Turma alterada com sucesso!")
                input("Tecle <ENTER> para continuar...")
            elif op_turma == '4':
                os.system('cls' if os.name == 'nt' else 'clear')
                print()
                print("############################################")
                print("#####         Exclui Turma             #####")
                print("############################################")
                print()
                cod_turma = input("##### Código da Turma: ")
                print()
                print("Turma excluída com sucesso!")
                input("Tecle <ENTER> para continuar...")
    
    elif op_princ == '4':
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        print("############################################")
        print("#####         Módulo Relatório         #####")
        print("############################################")
        print("##### 1 - Lista Geral de Alunos        #####")
        print("##### 2 - Lista Geral de Professores   #####")
        print("##### 3 - Lista Geral de Turmas        #####")
        print("##### 4 - Lista de Alunos por Turma    #####")
        print("##### 5 - Lista de Turmas p/ Professor #####")
        print("##### 0 - Retornar ao Menu Principal   #####")
        op_aluno = input("##### Escolha sua opção: ")
        print()
        input("Tecle <ENTER> para continuar...")
    
    elif op_princ == '5':
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        print("############################################")
        print("#####  Você está no Módulo Informações  ####")
        print("############################################")
        print()
        print("#####  Sistema de Gestão de uma Escola  ####")
        print("#####  Equipe de desenvolvimento:       ####")
        print("#####  * Flavius Gorgônio @flgorgonio   ####")
        print("#####  Licença Pública Geral GNU        ####")
        print("#####  www.gnu.org/licenses/gpl.html    ####")
        print()
        input("Tecle <ENTER> para continuar...")
    
    elif op_princ == '0':
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        print("############################################")
        print("#####  Você encerrou o programa, até logo! #")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")
    
    else:
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        print("############################################")
        print("#####   Você digitou uma opção inválida ####")
        print("############################################")
        print("#####                                   ####")
        print("#####      Retorne ao menu anterior     ####")
        print("#####         e tente novamente         ####")
        print("#####                                   ####")
        print("############################################")
        print()
        input("Tecle <ENTER> para continuar...")

print("Obrigado por usar o Sistema BitScola")